package CriarVendas;

import Cadastros.Tela_Cadastro;
import Formularios.Buscas;
import Tabelas.Vendas;
import Tabelas.Cliente;
import Tabelas.Vendedor;
import Tabelas.Produtos;
import Tela_Principal.Tela_Principal;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author diogo
 */
public class Tela_Vendas extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Vendas
     */
    public Tela_Vendas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtVendedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodbarras = new javax.swing.JTextField();
        btnConfirmarVenda = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        sMes = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sDia = new javax.swing.JSpinner();
        sAno = new javax.swing.JSpinner();
        btnVoltar = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Super mercado");

        jLabel2.setText("cpf do vendedor:");

        jLabel3.setText("cpf do cliente:");

        jLabel4.setText("Codigo de barras:");

        btnConfirmarVenda.setForeground(new java.awt.Color(0, 102, 0));
        btnConfirmarVenda.setText("Confirmar");
        btnConfirmarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVendaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Data da venda:");

        sMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jLabel6.setText("Dia");

        jLabel7.setText("Mês");

        jLabel8.setText("Ano");

        sDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        sAno.setModel(new javax.swing.SpinnerNumberModel(1990, 1990, 2024, 1));

        btnVoltar.setForeground(new java.awt.Color(0, 0, 255));
        btnVoltar.setText("voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodbarras, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sAno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(jLabel6)
                            .addGap(35, 35, 35)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabel1))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmarVenda)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sDia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sMes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sAno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodbarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarVenda)
                    .addComponent(btnVoltar))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVendaActionPerformed
        // TODO add your handling code here:
            String pagamento = JOptionPane.showInputDialog(null,
                    "Qual a forma de pagamento?",
                    "pagamento",1);
            if(pagamento != null){

                Vendedor vendedor = new Vendedor();
                Cliente cliente = new Cliente();
                Produtos produto = new Produtos();
                Vendas novaVenda = new Vendas();
                Buscas busca = new Buscas();
                
                String dia = (sDia.getValue().toString());
                String mes = (sMes.getValue().toString());
                String ano = (sAno.getValue().toString());
                String data = ano + "-" + mes + "-" + dia;
                
                long cpfVendedor = Long.parseLong(txtVendedor.getText());
                long cpfCliente = Long.parseLong(txtCliente.getText());
                long codBarras = Long.parseLong(txtCodbarras.getText());
                
                //verificação de exsitência do vendedor
                boolean vendedorExiste = false;
                if(busca.BuscarVendedor(cpfVendedor) == null){ 
                    UIManager.put("OptionPane.yesButtonText", "Cadastrar");
                    UIManager.put("OptionPane.noButtonText","Sair");
                    int op = JOptionPane.showConfirmDialog(null, 
                                "Vendedor inexistente",
                                "Não foi possivel realizar a venda",
                                0,0);
                    
                    switch (op){
                        
                        case 0: //realiza um novo cadastro
                            Tela_Cadastro cadastro = new Tela_Cadastro();
                            cadastro.setVisible(true);
                            this.setVisible(false);
                        break;
                        
                        default:
                        break;
                    }
                }else{
                    vendedor = busca.BuscarVendedor(cpfVendedor);
                    vendedorExiste = true;
                }
                
                //verificação de existência do Cliente
                boolean clienteExiste = false;
                if(busca.BuscarCliente(cpfCliente) == null){
                    UIManager.put("OptionPane.yesButtonText", "Cadastrar");
                    UIManager.put("OptionPane.nolButtonText","Sair");
                    int op = JOptionPane.showConfirmDialog(null, 
                                "Cliente inexistente",
                                "Não foi possivel realizar a venda",
                                0,0);
                    
                    switch (op){
                        
                        case 0: //realiza um novo cadastro
                            Tela_Cadastro cadastro = new Tela_Cadastro();
                            cadastro.setVisible(true);
                            this.setVisible(false);
                        break;
                        
                        default:
                        break;
                    }
                }else{
                    cliente = busca.BuscarCliente(cpfCliente);
                    clienteExiste = true;
                }
                
                //verificação de existência do Produto
                boolean produtoExiste = false;
                if(busca.PegarProduto(codBarras) == null){ 
                    UIManager.put("OptionPane.yesButtonText", "Cadastrar");
                    UIManager.put("OptionPane.noButtonText","Sair");
                    int op = JOptionPane.showConfirmDialog(null,
                                "Produto inexistente",
                                "Não foi possivel realizar a venda",
                                0,0);
                    
                    switch (op){
                        
                        case 0: //realiza um novo cadastro
                            Tela_Cadastro cadastro = new Tela_Cadastro();
                            cadastro.setVisible(true);
                            this.setVisible(false);
                        break;
                        
                        default:
                        break;
                    }
                }else{
                    produto = busca.PegarProduto(codBarras);
                    produtoExiste = true;
                }
                
                
                if((vendedorExiste) && (clienteExiste) && (produtoExiste)){
                    UIManager.put("OptionPane.yesButtonText","Confirmar");
                    UIManager.put("OptionPane.noButtonText", "Cancelar");
                    int confirmar = JOptionPane.showConfirmDialog(null,
                                            "Data: " + dia + "/" + mes + "/" + ano +
                                            "\nVendedor: " + vendedor.getNome_vendedor()+
                                            "\nCliente: " + cliente.getNome_cliente() +
                                            "\nProduto: " + produto.getNome_produto() +
                                            "\nForma de pagamento: " + pagamento,
                                            "Detalhes da compra",
                                            0,1);
                    if(confirmar == 0){
                        boolean resultado = novaVenda.CriarVenda(data,vendedor,cliente,produto,pagamento);
                        txtVendedor.setText("");
                        txtCliente.setText("");
                        txtCodbarras.setText("");
                        if(resultado == true){
                            JOptionPane.showMessageDialog(null, "venda realizada com sucesso");
                        }else if(resultado == false) {
                            JOptionPane.showMessageDialog(null,
                                "Não foi possivel realizar a venda",
                                "erro",
                                0);
                        }
                    }
                }   
            }
    }//GEN-LAST:event_btnConfirmarVendaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        Tela_Principal telaPrincipal = new Tela_Principal();
        this.setVisible(false);
        telaPrincipal.setVisible(true);
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConfirmarVenda;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JSpinner sAno;
    private javax.swing.JSpinner sDia;
    private javax.swing.JSpinner sMes;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodbarras;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
